# Generated by Django 5.0.1 on 2025-11-06 04:51

import apps.orders.models.order
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_add_order_name_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="order_comments/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "is_system_message",
                    models.BooleanField(
                        default=False,
                        help_text="System-generated message (e.g., 'Order status changed')",
                    ),
                ),
            ],
            options={
                "db_table": "order_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderCommentReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "👍 Like"),
                            ("heart", "❤️ Heart"),
                            ("check", "✅ Check"),
                        ],
                        default="like",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "order_comment_reactions",
            },
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_order_n_a1d48e_idx",
            old_name="orders_order_name_idx",
        ),
        migrations.RenameIndex(
            model_name="order",
            new_name="orders_deliver_89a875_idx",
            old_name="orders_delivery_time_idx",
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default=apps.orders.models.order.generate_order_number,
                help_text="VD: Đơn 1, Đơn 2, Đơn 3 (reset mỗi ngày)",
                max_length=50,
                verbose_name="Số đơn hàng (tự động theo ngày)",
            ),
        ),
        migrations.AddField(
            model_name="ordercomment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="ordercomment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordercommentreaction",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="orders.ordercomment",
            ),
        ),
        migrations.AddField(
            model_name="ordercommentreaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="ordercomment",
            index=models.Index(
                fields=["order", "created_at"], name="order_comme_order_i_29f41c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordercomment",
            index=models.Index(
                fields=["user", "created_at"], name="order_comme_user_id_6e0222_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordercommentreaction",
            index=models.Index(
                fields=["comment", "reaction_type"],
                name="order_comme_comment_10ecfb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ordercommentreaction",
            unique_together={("comment", "user", "reaction_type")},
        ),
    ]
